services:
  db:
    image: postgres:latest
    container_name: brainag-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: rigoni

  app:
    image: node:22-alpine
    container_name: brainag-node
    depends_on:
      - db
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "npm install && npx prisma migrate deploy && npm run build && npx prisma generate && npm run start:prod"
